#!/usr/bin/env python3
"""
Generates samples/test_input.gcode: a synthetic gcode file that mimics the
comment/thumbnail conventions real OrcaSlicer output uses, for testing
flashforge_gx_post.py without needing OrcaSlicer installed.

This is NOT a substitute for testing against real OrcaSlicer output, and
definitely not a substitute for a real FlashPrint 5 Creator 4 export (see
README.md "Open Questions"). It only exercises the metadata/thumbnail
parsing and binary packing logic.
"""

import base64
from io import BytesIO
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent


def build_thumbnail_block() -> str:
    img = Image.new("RGB", (16, 16), color=(30, 144, 255))
    buf = BytesIO()
    img.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")

    lines = [f"; thumbnail begin 16x16 {len(b64)}"]
    for i in range(0, len(b64), 78):
        lines.append("; " + b64[i : i + 78])
    lines.append("; thumbnail end")
    return "\n".join(lines)


def main() -> None:
    gcode = f"""; generated by OrcaSlicer 2.4.2 on 2026-08-05 (synthetic fixture for testing)
{build_thumbnail_block()}

; Executable_block_start
M118 X200 Y175 Z500 T0
M140 S60 T0
M104 S210 T0
M104 S0 T1
M654 P60
M653 S0
M656 S0
M107 T0
M107 T1
M204 S1000
M900 K0.000 T0
G90
G1 Z50.000 F420
M7 T0
M6 T0
M652
M108 T0
G1 Z0.2 F300
G1 X10 Y10 F3000
G1 X50 Y10 E5 F1200
G1 X50 Y50 E10 F1200
G1 X10 Y50 E15 F1200
G1 X10 Y10 E20 F1200
M107 T0
M107 T1
M104 S0 T0
M140 S0 T0
G162 Z F1800
M652
G91
M18
; Executable_block_end

; filament used [mm] = 320.45
; filament used [cm3] = 0.77
; filament used [g] = 0.96
; filament cost = 0.02
; estimated printing time (normal mode) = 0h 12m 34s
; total filament used [g] = 0.96

; orcaslicer_config = begin
; layer_height = 0.2
; first_layer_bed_temperature = 60,0
; nozzle_temperature = 210,0
; outer_wall_speed = 60
; machine_max_speed_x = 500,500
; orcaslicer_config = end
"""

    out_path = ROOT / "tests" / "samples" / "test_input.gcode"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(gcode, encoding="utf-8")
    print(f"wrote {out_path} ({len(gcode)} bytes)")


if __name__ == "__main__":
    main()
